import componentRegistry from "../../system/ComponentRegistry.ts";
import BackButton from "./back-button/BackButton.ts";
import Sidebar from "./sidebar/Sidebar.ts";
import ProfileListItem from "./profile-list-item/ProfileListItem.ts";
import ProfileAvatar from "./profile-avatar/ProfileAvatar.ts";
import ModalBlock from "./modal-block/ModalBlock.ts";
import Modal from "./modal/Modal.ts";
import MessagesHeader from "./messages-header/MessagesHeader.ts";
import ChatButton from "./chat-button/ChatButton.ts";
import ChatItem from "./chat-item/ChatItem.ts";
import DropdownMenu__Item from "./dropdown-menu/__item/DropdownMenu__Item.ts";
import DropdownMenu from "./dropdown-menu/DropdownMenu.ts";
import ErrorPage from "./error-page/ErrorPage.ts";
import FormField from "./form-field/FormField.ts";
import MessageInput from "./message-input/MessageInput.ts";
import MessageItem from "./message-item/MessageItem.ts";

componentRegistry(BackButton);
componentRegistry(ChatButton);
componentRegistry(ChatItem);
componentRegistry(DropdownMenu__Item);
componentRegistry(DropdownMenu);
componentRegistry(ErrorPage);
componentRegistry(FormField);
componentRegistry(MessageInput);
componentRegistry(MessageItem);
componentRegistry(MessagesHeader);
componentRegistry(Modal);
componentRegistry(ModalBlock);
componentRegistry(ProfileAvatar);
componentRegistry(ProfileListItem);
componentRegistry(Sidebar);