#!/usr/bin/env sh
  . "$(dirname -- "$0")/_/husky.sh"                                                                                                                                                                     
                                                                                                                                                                                                        
# Запуск линтеров на staged файлах
  npx lint-staged                                                                                                                                                                                       
                                                                                                                                                                                                        
# Запуск тестов
  npm test  